### ISSUE TITLE
Using "unsafe.Pointer" to cast from string to bytes can be unsafe?

### ISSUE THREAD

**Issue by mikn** [mikn/greddis#9]
Randomly got the below stacktrace when running the benchmarks. Not exactly sure how it could happen other than some magical fuckery by the bufio library.
Keeping it on the bug tracker to see if anyone runs into it.

```
panic: runtime error: slice bounds out of range [:9995941] with capacity 7453449

goroutine 265 [running]:
internal/poll.(*FD).Write(0xc0000cb180, 0xc003e08fdb, 0x9886a5, 0x71bb09, 0x0, 0x0, 0x0)
	/usr/lib/go-1.13/src/internal/poll/fd_unix.go:268 +0x432
net.(*netFD).Write(0xc0000cb180, 0xc003e08fdb, 0x9886a5, 0x71bb09, 0x1000, 0x0, 0x0)
	/usr/lib/go-1.13/src/net/fd_unix.go:220 +0x4f
net.(*conn).Write(0xc000010228, 0xc003e08fdb, 0x9886a5, 0x71bb09, 0x0, 0x0, 0x0)
	/usr/lib/go-1.13/src/net/net.go:196 +0x68
bufio.(*Writer).Write(0xc000127840, 0xc003e08fdb, 0x9886a5, 0x71bb09, 0xb, 0x0, 0x0)
	/usr/lib/go-1.13/src/bufio/bufio.go:625 +0x144
github.com/mikn/greddis.(*comm).writeBulkString(0xc0002d01e0, 0xc003e08000, 0x989680, 0x71cae4)
	/home/mikn/devel/greddis/command.go:77 +0x183
github.com/mikn/greddis.(*comm).add(0xc0002d01e0, 0x69f880, 0xc00030a1b0, 0x0)
	/home/mikn/devel/greddis/command.go:89 +0xe1
github.com/mikn/greddis.(*comm).addUnsafe(0xc0002d01e0, 0x69f880, 0xc00030a1b0, 0xc0002d01e0, 0x3)
	/home/mikn/devel/greddis/command.go:116 +0x48
github.com/mikn/greddis.(*client).Set(0xc0002d00f0, 0x7786a0, 0xc0000160e8, 0x71a68b, 0x7, 0x69f880, 0xc00030a1b0, 0x0, 0x6e32c0, 0x4)
	/home/mikn/devel/greddis/client.go:86 +0x516
github.com/mikn/greddis/benchmarks.greddisSet.func1(0xc0000da380)
	/home/mikn/devel/greddis/benchmarks/main_test.go:419 +0x289
testing.(*B).runN(0xc0000da380, 0x1)
	/usr/lib/go-1.13/src/testing/benchmark.go:190 +0xcc
testing.(*B).run1.func1(0xc0000da380)
	/usr/lib/go-1.13/src/testing/benchmark.go:230 +0x64
created by testing.(*B).run1
	/usr/lib/go-1.13/src/testing/benchmark.go:223 +0x7d
exit status 2
```

**Comment by mikn** [comment]
Further debugging found that it has to do with this.
```
	case *string:
		c.writeBytes(*(*[]byte)(unsafe.Pointer(d)))
```
Which went through the `default` case of `addUnsafe`

if the flow goes like this: 
```
func (c *comm) addUnsafe(item interface{}) error {
	switch d := item.(type) {
	case *string:
		c.add(*d)
```
to:
```
func (c *comm) add(item interface{}) *comm {
	switch d := item.(type) {
	case string:
		c.writeBytes(*(*[]byte)(unsafe.Pointer(&d)))
```

This doesn't seem to be a problem anymore... :thinking:

**Comment by mikn** [comment]
A guess is that it has something to do with the wrapping that happens for the magical `interface{}` switch cases and the optimizations surrounding them. I'll close this issue for now and leave a reference in the code.
